---
- name: Ensuring AWS IAM User does not exist
  amazon.aws.iam_user_info:
    name: "{{ users.aws.username }}"
  register: user_info_result

- name: Creating AWS IAM User
  amazon.aws.iam_user:
    name: "{{ users.aws.username }}"
    state: present
    password: "{{ users.aws.password }}"
    password_reset_required: false
  when: user_info_result.iam_users | length == 0

- name: Attaching AWS IAM Policy to IAM User
  amazon.aws.iam_user:
    name: "{{ users.aws.username }}"
    managed_policies: "{{ users.aws.policy }}"
    state: present

- name: Check if access key exists for the IAM user
  community.aws.iam_access_key_info:
    user_name: "{{ users.aws.username }}"
  register: iam_access_key_info_result

- name: Creating AWS Access key for IAM user
  community.aws.iam_access_key:
    user_name: "{{ users.aws.username }}"
    state: present
  register: iam_access_key_result
  when: iam_access_key_info_result.access_keys | length == 0

- name: Storing Credentials in home folder
  copy:
    content: "{{ iam_access_key_result.access_key.access_key_id }}:{{ iam_access_key_result.secret_access_key }}"
    dest: "./aws_credentials.txt"
    mode: "0600"
  when: iam_access_key_info_result.access_keys | length == 0