---
- name: Adding new user to Jenkins
  jenkins_script:
    url: "{{ users.jenkins.jenkins_host }}"
    user: "{{ users.jenkins.admin_username }}"
    password: "{{ users.jenkins.admin_password }}"
    script: |
      import jenkins.model.*
      import hudson.security.*

      def instance = Jenkins.getInstance()
      def existingUser = instance.securityRealm.allUsers.find {it.id == "{{ users.jenkins.new_username }}"}
      println "Value of existingUser: $existingUser"
      if (existingUser == null) {
        def hudsonRealm = new HudsonPrivateSecurityRealm(false)
        hudsonRealm.createAccount("{{ users.jenkins.new_username }}","{{ users.jenkins.new_password }}")
        instance.setSecurityRealm(hudsonRealm)
        instance.save()
      }
      else {
        println("user already exists")
      }
  register: result

- name: Printing result
  debug:
    var: result
