---
- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present
    update_cache: yes

- name: Configure dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
  notify: restart dnsmasq

- name: Create directory for custom dnsmasq configs
  file:
    path: /etc/dnsmasq.d
    state: directory
    mode: '0755'

- name: Create static records file
  template:
    src: static-records.conf.j2
    dest: /etc/dnsmasq.d/static-records.conf
  notify: restart dnsmasq

- name: Create custom CNAME records file
  template:
    src: custom-cname.conf.j2
    dest: /etc/dnsmasq.d/custom-cname.conf
  notify: restart dnsmasq

- name: Ensure dnsmasq service is running and enabled
  service:
    name: dnsmasq
    state: started
    enabled: yes

handlers:
  - name: restart dnsmasq
    service:
      name: dnsmasq
      state: restarted
