
name: Pull request tracker
on:
  pull_request:
    types: [opened]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git Pull_request details
      run: |
          echo "Pull request creator: ${{ github.event.pull_request.user.name }}"
          echo "Pull request title: ${{ github.event.pull_request.title }}"
          echo "Pull request number: ${{ github.event.pull_request.number }}"
          echo "Pull request url: ${{ github.event.pull_request.html_url }}"
          echo "Pull request reviewers: ${{ join(github.event.pull_request.requested_reviewers.*.name) }}"

    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "New pull_request open",
                          "subtitle": "PR No: #${{ github.event.pull_request.number }}"
                      },
                      "sections": [
                          {
                              "widgets": [
                                  {
                                     "keyValue": {
                                          "topLabel": "Creator",
                                          "content": "${{ github.event.pull_request.user.login }}"
                                      },
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Title",
                                          "content": "${{ github.event.pull_request.title }}"
                                      }
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Reviewers",
                                          "content": "- ${{ join(github.event.pull_request.requested_reviewers.*.login) }}"
                                      }
                                   },
                                   {
                                      "buttons": [
                                          {
                                              "textButton": {
                                                  "text": "VIEW PR",
                                                  "onClick": {
                                                      "openLink": {
                                                          "url": "${{ github.event.pull_request.html_url }}"
                                                      }
                                                  }
                                              }
                                          }
                                      ]
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }'
